import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './Home.module.scss'
import SideBar from './SideBar'
import Topbar from './Topbar'
import image from '../public/hinh_nen.jpg'
import BarComponent from './BarComponent'

const Home: NextPage = () => {
  return (
    <div >
      {/* <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}


      {/* <div className={styles.container}>
        <SideBar />
        <div>
          <Topbar />
          <Image
            src={image}
            alt="picture"
            width={100}
            height={100}
          />

        </div>
      </div> */}
      <BarComponent />
    </div>
  )
}

export default Home
